### ISSUE TITLE
iOS not returning NDEF messages

### ISSUE THREAD

**Issue by eddyinet** [appcelerator-modules/ti.nfc#18]
Saw this was an open issue at one point but I'm still not able to receive a valid response on iOS:

`Creating [object TiNfcNdefMessage] in a different context than the calling function. { messages = ( "<null>" ); }`

This is with "run-on-main-thread" as true. SDK 7.1.0.

**Comment by hansemannn** [comment]
Should be fixed by https://github.com/appcelerator-modules/ti.nfc/pull/19.
