### ISSUE TITLE
Android TagForeground example error

### ISSUE THREAD

**Issue by eddyinet** [appcelerator-modules/ti.nfc#20]
Running the stock TagForeground example on both 7.0.1 and 7.1.0 results in:

`
[ERROR] TiExceptionHandler: (main) [0,3844] - Message: Uncaught You must disable foreground dispatching while your activity is still resumed
[ERROR] TiExceptionHandler: (main) [1,3845] - Source: nfcAdapter.disableForegroundDispatch();
`

This is with:

`<property name="run-on-main-thread" type="bool">true</property>`

**Comment by eddyinet** [comment]
Update... this might be related to "intent-filter-new-task" not working as per:

https://jira.appcelerator.org/browse/TIMOB-25776

Looks like a new activity might be created each time on a tag read causing the "disableForegroundDispatch" call to fail.

**Comment by matpag** [comment]
I'm not able to create a foreground activity without get into this error.... The module has a bug

**Comment by matpag** [comment]
Seems that i've solved changing this property:
`<property name="run-on-main-thread" type="bool">false</property>`

**Comment by hansemannn** [comment]
@garymathews Should we track this?
