### ISSUE TITLE
Unable to get current activity

### ISSUE THREAD

**Issue by PietroGranati** [appcelerator-modules/ti.nfc#21]
I'm porting my app from SDK 6.x to the lastest 7.x but I've encountered some problems, the app doesn't start anymore and after removing all modules and re-adding one at time I figured that ti.nfc is the problem.
The log is this one:
`-- Start application log -----------------------------------------------------
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[INFO] :   TiApplication: (main) [90,90] Titanium 7.1.1 (2018/04/19 11:11 undefined)
[INFO] :   MultiDex: VM with version 2.1.0 has multidex support
[INFO] :   MultiDex: install
[INFO] :   MultiDex: VM has multidex support, MultiDex support library is disabled.
[INFO] :   TiApplication: (main) [27,117] Analytics have been disabled
[WARN] :   TiAndroid: (main) [2470,2587] Application instance no longer available. Unable to get current activity.
[WARN] :   TiAndroid: (main) [2,2589] Application instance no longer available. Unable to get current activity.
[WARN] :   TiAndroid: (main) [0,2589] Application instance no longer available. Unable to get current activity.
`
The last 3 lines of WARN blocks everything and crash the app.

**Comment by PietroGranati** [comment]
I've fixed it myself, I've tryed to rebuild the module modifying the build.properties to the last updates:

titanium.platform=/Users/xxx/Library/Application Support/Titanium/mobilesdk/osx/7.0.0.GA/android
android.platform=/Users/xxx/Library/android-sdk-macosx/platforms/android-26
google.apis=/Users/xxx/Library/android-sdk-macosx/add-ons/addon-google_apis-google-18
android.ndk=/Users/xxx/Library/android-ndk-r16b

**Comment by hansemannn** [comment]
Thanks! Please build modules with `appc run -p android --build-only` nowadays, which will use the proper config automatically.
