### ISSUE TITLE
Cannot set required false to uses-feature in SDK 8

### ISSUE THREAD

**Issue by PietroGranati** [appcelerator-modules/ti.nfc#28]
Since the release of SDK 8 the required=true inside the timodule.xml forces all the app to have required=true and reduce drastically the device avaiability on play store.

https://jira.appcelerator.org/browse/AC-6328

I've resolved removing the required in the timodule.xml

**Comment by jquick-axway** [comment]
This issue was introduced by Titanium 8.0.2 and resolved in 8.1.1 by this ticket...
https://jira.appcelerator.org/browse/TIMOB-27304

**Comment by PietroGranati** [comment]
The same problem with the new v.4.0 and SDK 9

**Comment by PietroGranati** [comment]
Fixed rebuilding NFC module with required=false, modifying the timodule.xml did not work
