### ISSUE TITLE
Getting runtime error, help please

### ISSUE THREAD

**Issue by cmtanko** [appcelerator-modules/ti.nfc#56]
I am trying to use the module, enabled NFC in identified, with new provision profile and running on iPhone XS but getting error
 
`{“column”:23,“nativeStack”:“3   TitaniumKit0x00000001054b4644 -[TiProxy addEventListener:] + 312\n4   CoreFoundation  0x0000000185157774 4FBDF167-161A-324C-A233-D516922C67E5 + 1238900\n5   CoreFoundation  0x000000018502ad44 4FBDF167-161A-324C-A233-D516922C67E5 + 7492\n6   TitaniumKit0x00000001054b1eac -[KrollMethod call:] + 1360\n7   TitaniumKit0x00000001054b1080 __KrollCallAsFunction_block_invoke + 36\n8   TitaniumKit0x00000001054b0e90 KrollCallAsFunction + 396\n9   JavaScriptCore  0x000000018e83898c 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 3033484\n10  JavaScriptCore  0x000000018ef207e4 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 10274788\n11  JavaScriptCore  0x000000018e7a1814 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2414612\n12  JavaScriptCore  0x000000018e7a1844 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2414660\n13  JavaScriptCore  0x000000018e7a2b20 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2419488\n14  JavaScriptCore  0x000000018e7a1844 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2414660\n15  JavaScriptCore  0x000000018e7a2b20 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2419488\n16  JavaScriptCore  0x000000018e7a1844 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2414660\n17  JavaScriptCore  0x000000018e7a1844 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2414660\n18  JavaScriptCore  0x000000018e77ab58 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 2255704\n19  JavaScriptCore  0x000000018ee09c10 74545BAC-15FF-320D-A90B-8F89F75E39C1 + 9133072\n20  JavaScriptCore  0x000000018f08c40c _ZN3JSC8evaluateEPNS_14JSGlobalObjectERKNS_10SourceCodeENS_7JSValueERN3WTF8NakedPtrINS_9ExceptionEEE + 272\n21  JavaScriptCore  0x000000018e82f51c JSEvaluateScript + 696\n22  TitaniumKit0x00000001054aea60 -[KrollEval jsInvokeInContext:exception:] + 172”,“message”:“Invalid type passed to function”,“stack”:“[native code]\naddListener@file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/alloy/controllers/BaseController.js:430:23\nController@file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/alloy/controllers/login.js:270:76\nfile:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/alloy.js:428:48\nController@file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/alloy/controllers/index.js:53:23\nfile:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/alloy.js:428:48\nfile:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/app.js:158:23\nglobal code@file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/app.js:161:70\nrequire@[native code]\nfile:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/ti.main.js:14290:10\nloadAsync@file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/ti.main.js:14236:13\nglobal code@file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/ti.main.js:14287:10”,“nativeReason”:“expected: Function, was: NSNull”,“type”:“error”,“line”:430,“sourceURL”:“file:///private/var/containers/Bundle/Application/A41D4868-1CFE-4F03-B0EE-7CD895B99E48/my.app/alloy/controllers/BaseController.js”,“bubbles”:true,“source”:{},“cancelBubble”:false}`
[ERROR] This device does not support NFC capabilities! (edited)

**Comment by hansemannn** [comment]
The error is because you pass "null" into a method that requires a function (in your login.js).
